"""Exit logic module.

Implements the multi-layer exit system for the RSI strategy:

1. Partial exit at 1.5R profit (close 50% of position).
2. Stop moves to break-even at 1.0R.
3. Trailing stop via RSI 15M cross (close below 50 for longs, above 50 for shorts).
4. Hard stop by price (initial stop-loss).
5. Time stop: close position after max holding period (36 hours default).
"""

from __future__ import annotations

from dataclasses import dataclass, field
from enum import Enum
from typing import List, Optional

from app.core.signal import SignalType


class ExitReason(str, Enum):
    """Why a position was closed or reduced."""

    PARTIAL_R = "partial_r"  # Hit 1.5R, partial close
    TRAILING_RSI = "trailing_rsi"  # RSI 15M crossed against position
    HARD_STOP = "hard_stop"  # Hit price stop
    TIME_STOP = "time_stop"  # Exceeded max holding period
    MANUAL = "manual"  # Manual close
    LIQUIDATION = "liquidation"  # Liquidated by venue


@dataclass(frozen=True)
class ExitAction:
    """An exit instruction generated by the exit logic."""

    should_exit: bool
    reason: Optional[ExitReason] = None
    close_pct: float = 1.0  # fraction of position to close (0.0-1.0)
    new_stop: Optional[float] = None  # updated stop price, if changed

    @property
    def is_partial(self) -> bool:
        return self.should_exit and self.close_pct < 1.0


@dataclass
class PositionTracker:
    """Tracks the state of an open position for exit logic evaluation.

    All price levels are absolute (not percentage).
    """

    entry_price: float
    stop_price: float  # initial hard stop
    direction: SignalType  # LONG or SHORT
    entry_time_ms: int  # unix ms timestamp of entry
    position_size: float = 1.0  # normalized (1.0 = full size)
    partial_exited: bool = False
    be_moved: bool = False  # has stop been moved to break-even
    r_multiple: float = 0.0  # current R-multiple of unrealized PnL

    @property
    def risk_distance(self) -> float:
        """Distance from entry to initial stop (the 'R' distance)."""
        if self.direction == SignalType.LONG:
            return self.entry_price - self.stop_price
        return self.stop_price - self.entry_price

    def compute_r_multiple(self, current_price: float) -> float:
        """Compute the current R-multiple of the position."""
        risk = self.risk_distance
        if risk <= 0:
            return 0.0
        if self.direction == SignalType.LONG:
            pnl = current_price - self.entry_price
        else:
            pnl = self.entry_price - current_price
        self.r_multiple = pnl / risk
        return self.r_multiple


class ExitManager:
    """Evaluates exit conditions for an open position.

    Usage:
        manager = ExitManager(max_hold_hours=36, partial_r=1.5, be_r=1.0)
        action = manager.evaluate(tracker, current_price, current_time_ms, rsi_15m)
        if action.should_exit:
            # execute exit
    """

    def __init__(
        self,
        max_hold_hours: int = 36,
        partial_r: float = 1.5,
        be_r: float = 1.0,
        partial_close_pct: float = 0.5,
        trailing_rsi_threshold: float = 50.0,
    ) -> None:
        self._max_hold_ms = max_hold_hours * 3600 * 1000
        self._partial_r = partial_r
        self._be_r = be_r
        self._partial_close_pct = partial_close_pct
        self._trailing_rsi_threshold = trailing_rsi_threshold

    def evaluate(
        self,
        tracker: PositionTracker,
        current_price: float,
        current_time_ms: int,
        rsi_15m: Optional[float] = None,
    ) -> ExitAction:
        """Evaluate all exit conditions for the position.

        Checks are ordered by priority:
        1. Hard stop hit
        2. Time stop
        3. Partial exit at target R
        4. Break-even stop move
        5. Trailing RSI exit

        Args:
            tracker: Current position state.
            current_price: Latest price.
            current_time_ms: Current time in unix ms.
            rsi_15m: Current RSI on the 15M timeframe (for trailing exit).

        Returns:
            ExitAction indicating what to do.
        """
        r_multiple = tracker.compute_r_multiple(current_price)

        # 1. Hard stop hit
        if tracker.direction == SignalType.LONG and current_price <= tracker.stop_price:
            return ExitAction(should_exit=True, reason=ExitReason.HARD_STOP, close_pct=1.0)
        if tracker.direction == SignalType.SHORT and current_price >= tracker.stop_price:
            return ExitAction(should_exit=True, reason=ExitReason.HARD_STOP, close_pct=1.0)

        # 2. Time stop
        hold_duration = current_time_ms - tracker.entry_time_ms
        if hold_duration >= self._max_hold_ms:
            return ExitAction(should_exit=True, reason=ExitReason.TIME_STOP, close_pct=1.0)

        # 3. Partial exit at target R
        if not tracker.partial_exited and r_multiple >= self._partial_r:
            new_stop = tracker.entry_price  # move stop to BE on partial
            return ExitAction(
                should_exit=True,
                reason=ExitReason.PARTIAL_R,
                close_pct=self._partial_close_pct,
                new_stop=new_stop,
            )

        # 4. Break-even stop move
        if not tracker.be_moved and r_multiple >= self._be_r:
            be_stop = tracker.entry_price
            return ExitAction(
                should_exit=False,
                reason=None,
                new_stop=be_stop,
            )

        # 5. Trailing RSI exit (only after partial or BE move)
        if (tracker.partial_exited or tracker.be_moved) and rsi_15m is not None:
            if tracker.direction == SignalType.LONG and rsi_15m < self._trailing_rsi_threshold:
                return ExitAction(should_exit=True, reason=ExitReason.TRAILING_RSI, close_pct=1.0)
            if tracker.direction == SignalType.SHORT and rsi_15m > self._trailing_rsi_threshold:
                return ExitAction(should_exit=True, reason=ExitReason.TRAILING_RSI, close_pct=1.0)

        return ExitAction(should_exit=False)

    def apply_exit_action(self, tracker: PositionTracker, action: ExitAction) -> None:
        """Mutate the tracker to reflect an executed exit action.

        Call this after you have executed the exit in the market.

        Args:
            tracker: Position tracker to update.
            action: The exit action that was executed.
        """
        if action.new_stop is not None:
            tracker.stop_price = action.new_stop
            if action.new_stop == tracker.entry_price:
                tracker.be_moved = True

        if action.should_exit:
            if action.reason == ExitReason.PARTIAL_R:
                tracker.partial_exited = True
                tracker.position_size *= (1.0 - action.close_pct)
            else:
                tracker.position_size = 0.0
